# -*- coding: utf-8 -*-
"""TFG_Phishing_Detection_EDA_and_Baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aEuJNUbT2NqUts5OW2ms6db4aCO5aOJE

# **TFG: Sistema de detección de phishing de sitios web mediante técnicas de machine learning y análisis dinámico de URLs**

## **EDA - Phishing Website Dataset (Zenodo)**

### **Objetivo:** cargar los ficheros phishing.csv y not-phishing.csv, unirlos en un único dataset etiquetado y realizar un análisis exploratorio básico (tamaño, columnas, nulos, duplicados y balanceo de clases).
"""

# Cargamos las librerías necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Cargamos los csv que tenemos
df_phishing = pd.read_csv("phishing.csv")
df_not_phishing = pd.read_csv("not-phishing.csv")

# Observamos las filas y columnas que tiene cada csv
df_phishing.shape, df_not_phishing.shape

# Creamos la variables objetivo (label)
df_phishing["label"] = 1
df_not_phishing["label"] = 0

# Alineamos las columnas comunes para unir ambos datasets

common_columns = list(set(df_phishing.columns) & set(df_not_phishing.columns))

df_phishing_common = df_phishing[common_columns]
df_not_phishing_common = df_not_phishing[common_columns]

df = pd.concat([df_phishing_common, df_not_phishing_common], ignore_index=True)

# Datasets unidos
df.shape

# Mostramos los nombres de las columnas del dataset
df.columns

# Mostramos las primeras filas del dataset
df.head()

# Información general del dataset (tipos de datos y valores no nulos)
df.info()

# Contamos los valores nulos que hay por columna
df.isnull().sum().sort_values(ascending=False)

# Eliminamos las columnas que están completamente vacías
df = df.dropna(axis=1, how="all")

# Comprobamos el número de columnas tras la limpieza inicial que hemos hecho
df.shape

# Comprobamos el número de filas duplicadas que hay
df.duplicated().sum()

# Contamos el número de ejemplos que hay por clase
df["label"].value_counts()

# Visualizamos una distribución de clases
df["label"].value_counts().plot(kind="bar")
plt.xlabel("Label")
plt.ylabel("Número de ejemplos")
plt.title("Distribución de clases")
plt.show()

"""### Limpieza y selección de columnas"""

# Creamos una copia del dataset para trabajar con ella
df_clean = df.copy()

# Eliminamos las columnas que no son relevantes para el modelado
columns_to_drop = [
    "_id",
    "folder_path",
    "features.html",
    "features.text",
    "features.css",
    "whois_raw_text",
    "scan_date"
]

df_clean = df_clean.drop(columns=columns_to_drop)

# Comprobamos las dimensiones tras la eliminación de columnas
df_clean.shape

# Mostramos las columnas finales tras la limpieza inicial
df_clean.columns

"""### Tratamiento de valores nulos"""

# Identificamos las columnas numéricas y categóricas
numeric_cols = df_clean.select_dtypes(include=["int64", "float64"]).columns
categorical_cols = df_clean.select_dtypes(include=["object"]).columns

# Rellenamos los valores nulos en las columnas numéricas con la mediana
for col in numeric_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

# Rellenamos los valores nulos en columnas categóricas con 'unknown'
for col in categorical_cols:
    df_clean[col] = df_clean[col].fillna("unknown")

# Comprobamos que no quedan valores nulos
df_clean.isnull().sum().sum()

"""### Preparamos el dataset para Machine Learning (encoding)"""

# Separamos variables (X) y etiqueta (y)
X = df_clean.drop(columns=["label"])
y = df_clean["label"]

# Aplicamos one-hot encoding a las variables categóricas
X_encoded = pd.get_dummies(X, drop_first=True)

# Comprobamos las dimensiones antes y después del encoding
X.shape, X_encoded.shape

"""Como vemos que la cantidad de columnas asciende mucho al hacer el one-hot encoding vamos a ir por otro camino

### Vemos cuántos valores únicos tienen algunas columnas (para decidir qué codificar)
"""

# Vemos la cardinalidad (número de valores únicos) de las columnas categóricas principales
cols_check = ["protocol", "security_state", "security_protocol", "security_issuer", "language", "remote_ip_country"]
df_clean[cols_check].nunique()

"""Elegimos las 3 primeras (protocol, security_state y security_protocol) que son las que tienen menor número de cardinalidad

### Extracción de características léxicas de la URL
"""

# Longitud total de la URL
df_clean["url_length"] = df_clean["url"].apply(len)

# Número de subdominios en la URL
df_clean["num_subdomains"] = df_clean["domain"].apply(lambda x: x.count("."))

# Número de dígitos en la URL
df_clean["num_digits"] = df_clean["url"].apply(lambda x: sum(char.isdigit() for char in x))

# Número de caracteres especiales en la URL (símbolos típicos usados en phishing)
special_chars = ["@", "-", "_", "?", "=", "&", "%"]
df_clean["num_special_chars"] = df_clean["url"].apply(
    lambda x: sum(x.count(char) for char in special_chars)
)

# Detectamos si la URL contiene una dirección IP
df_clean["has_ip"] = df_clean["url"].apply(
    lambda x: 1 if any(char.isdigit() for char in x.split("//")[-1].split("/")[0]) and "." in x else 0
)

# Mostramos algunas filas con las nuevas características
df_clean[["url_length", "num_subdomains", "num_digits", "num_special_chars", "has_ip"]].head()

"""### Construimos el dataset final para Machine Learning"""

# Seleccionamos las columnas numéricas que son útiles
numeric_features = [
    "assets_downloaded",
    "remote_ip_asn",
    "whois_domain_age",
    "url_length",
    "num_subdomains",
    "num_digits",
    "num_special_chars",
    "has_ip"
]

# Seleccionamos las columnas categóricas de baja cardinalidad
categorical_features = [
    "protocol",
    "security_state",
    "security_protocol"
]

# Creamos el dataset final para ML
X_final = df_clean[numeric_features + categorical_features]
y_final = df_clean["label"]

# Aplicamos one-hot encoding solo a variables categóricas seleccionadas
X_final_encoded = pd.get_dummies(X_final, columns=categorical_features, drop_first=True)

# Dimensiones finales del dataset para ML
X_final.shape, X_final_encoded.shape

"""### División del dataset en entrenamiento y prueba"""

# Dividimos el dataset en entrenamiento y prueba

X_train, X_test, y_train, y_test = train_test_split(
    X_final_encoded,
    y_final,
    test_size=0.2,
    random_state=30,
    stratify=y_final
)

# Entrenamos el modelo baseline: Regresión Logística
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)

"""Como hay features en escalas muy distintas hay variables que hacen que el optimizador necesite más iteraciones, entonces lo que ahremos será estandarizar (escalar) las variables antes de entrenar Logistic Regression."""

log_reg = Pipeline(steps=[
    ("scaler", StandardScaler(with_mean=False)),
    ("model", LogisticRegression(max_iter=5000))
])

log_reg.fit(X_train, y_train)

# Predicciones del modelo (clase y probabilidad)
y_pred = log_reg.predict(X_test)
y_proba = log_reg.predict_proba(X_test)[:, 1]

# Evaluamos el modelo con algunas métricas estándar
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_proba)

metrics_df = pd.DataFrame({
    "Métrica": ["Accuracy", "Precision", "Recall", "F1-score", "ROC-AUC"],
    "Valor": [accuracy, precision, recall, f1, roc_auc]
})

metrics_df

"""### Random Forest (comparación)

"""

# Entrenamos el modelo baseline: Random Forest
rf = RandomForestClassifier(
    n_estimators=300,
    random_state=30,
    n_jobs=-1
)

rf.fit(X_train, y_train)

# Predicciones con Random Forest
y_pred_rf = rf.predict(X_test)
y_proba_rf = rf.predict_proba(X_test)[:, 1]

# Métricas de evaluación del modelo Random Forest
accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)
roc_auc_rf = roc_auc_score(y_test, y_proba_rf)

metrics_rf_df = pd.DataFrame({
    "Métrica": ["Accuracy", "Precision", "Recall", "F1-score", "ROC-AUC"],
    "Valor": [accuracy_rf, precision_rf, recall_rf, f1_rf, roc_auc_rf]
})

metrics_rf_df

"""### Tabla final comparativa (Regresión Logísitica vs Random Forest)"""

# Creamos la tabla comparativa de métricas (Logistic Regression vs Random Forest)
comparison_df = pd.DataFrame({
    "Modelo": ["Logistic Regression", "Random Forest"],
    "Accuracy": [accuracy, accuracy_rf],
    "Precision": [precision, precision_rf],
    "Recall": [recall, recall_rf],
    "F1-score": [f1, f1_rf],
    "ROC-AUC": [roc_auc, roc_auc_rf]
})

comparison_df.round(4)

# Matriz de confusión para Random Forest
cm_rf = confusion_matrix(y_test, y_pred_rf)
disp = ConfusionMatrixDisplay(confusion_matrix=cm_rf, display_labels=["Legítimo", "Phishing"])
disp.plot()
plt.title("Matriz de confusión de Random Forest")
plt.show()

"""910 Verdaderos Negativos (TN)
--> URLs legítimas correctamente clasificadas como legítimas.

922 Verdaderos Positivos (TP)
--> URLs de phishing correctamente detectadas como phishing.

139 Falsos Positivos (FP)
--> URLs legítimas marcadas erróneamente como phishing
(molesto, pero menos crítico en ciberseguridad).

108 Falsos Negativos (FN)
--> URLs de phishing no detectadas
(esto es lo más peligroso, y aquí el número que nos ha dado es relativamente bajo)
"""

# Convertimos la columna scan_date a formato datetime (por si está como texto)
df['scan_date'] = pd.to_datetime(df['scan_date'], errors='coerce')

# Comprobamos el tipo de dato
df['scan_date'].dtype

# Obtenemos la fecha más antigua y más reciente del dataset
fecha_min = df['scan_date'].min()
fecha_max = df['scan_date'].max()

fecha_min, fecha_max

# Extraemos año-mes
df['year_month'] = df['scan_date'].dt.to_period('M')

# Conteo por mes
df['year_month'].value_counts().sort_index()